name: cassandra-lab

services:
  cass1:
    image: cassandra:4.1.12
    container_name: cass1
    networks: [cassnet]
    ports: ["9042:9042"]
    cap_add: [NET_ADMIN]
    environment:
      CASSANDRA_CLUSTER_NAME: consistency_lab
      CASSANDRA_SEEDS: cass1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    healthcheck:
      test: ["CMD-SHELL", "nodetool statusbinary | grep -q running && nodetool netstats | grep -q 'Mode: NORMAL'"]
      interval: 20s
      timeout: 15s
      retries: 20
      start_period: 60s

  cass2:
    image: cassandra:4.1.12
    container_name: cass2
    networks: [cassnet]
    ports: ["9043:9042"]
    cap_add: [NET_ADMIN]
    environment:
      CASSANDRA_CLUSTER_NAME: consistency_lab
      CASSANDRA_SEEDS: cass1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    healthcheck:
      test: ["CMD-SHELL", "nodetool statusbinary | grep -q running && nodetool netstats | grep -q 'Mode: NORMAL'"]
      interval: 20s
      timeout: 15s
      retries: 20
      start_period: 60s
    depends_on:
      cass1:
        condition: service_healthy

  cass3:
    image: cassandra:4.1.12
    container_name: cass3
    networks: [cassnet]
    ports: ["9044:9042"]
    cap_add: [NET_ADMIN]
    environment:
      CASSANDRA_CLUSTER_NAME: consistency_lab
      CASSANDRA_SEEDS: cass1
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    healthcheck:
      test: ["CMD-SHELL", "nodetool statusbinary | grep -q running && nodetool netstats | grep -q 'Mode: NORMAL'"]
      interval: 20s
      timeout: 15s
      retries: 20
      start_period: 60s
    depends_on:
      cass2:
        condition: service_healthy

networks:
  cassnet:
    driver: bridge
