set -euo pipefail
cd "$(dirname "$0")/.."

echo "==> [1/5] Launching the cluster..."
docker compose up -d --wait --wait-timeout 600

echo
echo "==> [2/5] Checking status..."
docker exec cass1 nodetool status
echo
docker exec cass1 nodetool describecluster | sed -n '1,8p'

echo
echo "==> [3/5] Building up keyspace and tables..."
for attempt in 1 2 3 4 5 6; do
  if docker exec -i cass1 cqlsh < scripts/setup_keyspace.cql 2>/tmp/cqlsh_err; then
    echo "  keyspace 就绪 (第 $attempt 次尝试)"
    break
  fi
  if [ "$attempt" = 6 ]; then
    echo "  Failed as the last attempt:" >&2
    cat /tmp/cqlsh_err >&2
    exit 1
  fi
  echo "  The $attempt -th attempt not responding, retrying after 8s ..."
  sleep 8
done
docker exec cass1 cqlsh -e "DESCRIBE TABLE consistency_lab.kv;" \
  | grep -E "read_repair|speculative_retry" || true

echo
echo "==> [4/5] Setting up Python virtual env & drivers..."
if [ ! -d .venv ]; then python3 -m venv .venv; fi
./.venv/bin/pip install -q --upgrade pip
./.venv/bin/pip install -q -r requirements.txt

echo
echo "==> Now confirming each session corresponds to distinct note..."
./.venv/bin/python -c "
import sys; sys.path.insert(0,'experiments')
from common import connect_nodes
n = connect_nodes()
[x.shutdown() for x in n.values()]
"

echo
echo "==> [5/5] Logging env info into results/environment.txt"
mkdir -p results
{
  echo "# env snapshot taken (generated by scripts/bootstrap.sh)"
  echo "Timestamp: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo
  echo "Cassandra image tag : $(grep -m1 'image:' docker-compose.yml | awk '{print $2}')"
  echo "Cassandra image digest : $(docker image inspect "$(grep -m1 'image:' docker-compose.yml | awk '{print $2}')" --format '{{.Id}}')"
  echo "Cassandra version     : $(docker exec cass1 cqlsh -e 'SELECT release_version FROM system.local;' 2>/dev/null | sed -n '4p' | tr -d ' ')"
  echo "Python             : $(./.venv/bin/python -V 2>&1)"
  echo "cassandra-driver   : $(./.venv/bin/python -c 'import cassandra; print(cassandra.__version__)')"
  echo "Docker             : $(docker version --format '{{.Server.Version}}' 2>/dev/null)"
  echo "Host             : $(uname -srm)"
} | tee results/environment.txt

echo
echo "Environment ready. Next steps:"
echo "  ./scripts/inject_latency.sh                 # Inject replication latency"
echo "  ./.venv/bin/python experiments/ryw_test.py -n 1000"
